

Gender.create!(:name => 'Both')
Gender.create!(:name => 'Women')
Gender.create!(:name => 'Men')
Author.create!(:name => 'Shakespeare')

Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'As You Like It')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'The Comedy of Errors')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Cymbeline')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Loves Labour''s Lost')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'The Merchant of Venice')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Much Ado About Nothing')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'The Taming of the Shrew')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Twelfth Night, Or What You Will')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'All''s Well That Ends Well')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Measure for Measure')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Merry Wives of Windsor')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Merchant of Venice')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'A Midsummer Night''s Dream')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'The Tempest')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Troilus and Cressida')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Two Gentlemen of Verona')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'The Winter''s Tale')
Play.create!(:author_id => 1, :classification => 'Comedy', :title => 'Pericles, Prince of Tyre')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry IV i')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry IV ii')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry V')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry VI i')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry VI ii')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry VI iii')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Henry VIII')
Play.create!(:author_id => 1, :classification => 'History', :title => 'King John')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Richard II')
Play.create!(:author_id => 1, :classification => 'History', :title => 'Richard III')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Antony & Cleopatra')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Coriolanus')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Hamlet')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'King Lear')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Macbeth')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Othello')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Romeo and Juliet')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Timon of Athens')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Titus Andronicus')
Play.create!(:author_id => 1, :classification => 'Tragedy', :title => 'Julius Caesar')



